### ISSUE TITLE
Does not work with scRNA-seq BAMs

### ISSUE THREAD

**Issue by johnchamberlin** [google/best#7]
I'm trying to use the tool on some single-cell RNA-seq data but it does not work. I think there is some error with the mapq field.

`thread '<unnamed>' panicked at src/stats.rs:324:57:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/stats.rs:324:57:
called `Option::unwrap()` on a `None` value`

I have tried BAMs from both CellRanger and STARsolo tools. Any suggestion on how to debug? I would share an example read but it doesn't throw the error if I provide it a BAM file  which I cropped to contain only the first read. 

Thanks,

**Comment by Daniel-Liu-c0deb0t** [comment]
Thanks for reporting this issue! `best` currently expects the `mapq` value to exist for all mapped BAM records. Can you quickly double check if there are any mapped records where the `mapq` does not exist (`*`)?

**Comment by johnchamberlin** [comment]
mapq has values 0,1,3, and 255. 
`samtools view <bam> | cut -f 5 | sort | uniq -c`

I downloaded this smaller file from 10x genomics to confirm. 
https://www.10xgenomics.com/resources/datasets/1-k-pbm-cs-from-a-healthy-donor-v-2-chemistry-3-standard-3-0-0

**Comment by Daniel-Liu-c0deb0t** [comment]
Ok, I will try to reproduce the issue with the 10x dataset.

**Comment by Daniel-Liu-c0deb0t** [comment]
Oh wait I just realized, 255 in `mapq` technically means that it is missing.

**Comment by johnchamberlin** [comment]
STAR uses 255 to signify uniquely mapped reads.

**Comment by Daniel-Liu-c0deb0t** [comment]
Ok I made a PR (#8) with a workaround for the BAM parser to handle this edge case. ~~Feel free to use the version in my [fork](https://github.com/Daniel-Liu-c0deb0t/best) for now, I'm not sure when this repo will be updated.~~

**Comment by Daniel-Liu-c0deb0t** [comment]
Merged!
